AllCops:
  Exclude:
    - 'vendor/**/*'
# to exclude files

Documentation:
  Enabled: false

# Line is too long
Metrics/LineLength:
  Max: 120
# or
  Enabled: false

# Assignment Branch Condition size for plot_defaults is too high
Metrics/AbcSize:
  Enabled: false

# Method has too many lines
Metrics/MethodLength:
  Enabled: false
